#!/usr/bin/env bash

COMMAND_NAME=SDKMan
echo "#################################################################################################################"
echo "Check installation for $COMMAND_NAME"
if sdk version > /dev/null; then
  # SDKMAN is installed
  echo "$COMMAND_NAME is installed"
  sdk version
else
  # SDKMAN is not installed
  echo "$COMMAND_NAME is not installed. Installing..."
  curl -s "https://get.sdkman.io" | bash
  source "$HOME/.sdkman/bin/sdkman-init.sh"
fi
echo "#################################################################################################################"
echo ""