#!/usr/bin/env bash

echo "#################################################################################################################"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"
  
# NEED TO IMPLEMENT RELOADING TERMINAL
#FIXME:
echo "TODO: Need to implement reloading terminal"
echo "#################################################################################################################"
echo ""