#!/usr/bin/env bash

# Tools for Development

# Java Development Toolkit – JDK
source "$HOME/.sdkman/bin/sdkman-init.sh"

sdk install java 18.0.1.1-open
# Maven
sdk install maven
# Gradle
sdk install gradle

# JetBrains Toolkit
sh install-by-brew-cask jetbrains-toolbox "JetBrains Toolbox"

# Docker
sh install-by-brew docker "Docker"
sh install-by-brew docker-compose "Docker Compose"
sh install-by-brew-cask rancher "Rancher"

# Graphviz and PlantUML
sh install-by-brew graphviz "Graphviz"
sh install-by-brew plantuml "Plant UML"
