#!/usr/bin/env bash

# Recommended Set
echo "Start installation of Recommended Set..."
sh install-by-brew-cask google-chrome "Google Chrome"
sh install-by-brew-cask sublime-text "Sublime Text"
sh install-by-brew-cask protonvpn "ProtonVPN"
# sh install-by-brew-cask mullvadvpn "Mullvad VPN"
sh install-by-brew fish "Fish Shell"
sh install-by-brew awk "AWK"
sh install-by-brew iterm2 "iTerm2"
sh install-by-brew bat "Bat"
sh install-by-brew-cask fsnotes "FSNotes"
sh install-by-brew eza "EZA"
sh install-by-brew-cask chatgpt "ChatGPT"
