#!/usr/bin/env bash

print_help() {
    echo "    Update Maven Password"
    echo "  Tool for Generating new Maven Master Password, replace it in 'settings-security.xml'"
    echo "and then generating Maven Password with replacing it in 'settings.xml'."
    echo ""
    echo "Synopsis:"
    echo " – update-maven-password"
    echo " – update-maven-password --help"
    echo ""
    echo "Usage:"
    echo " – update-maven-password: create new Master Password and Password using user input and update settings files"
    echo " – update-maven-password --help: print this message and exit"
}

print_variables() {
  echo "Variables:"
  echo "  MASTER_PASSWORD: $MASTER_PASSWORD"
  echo "  PASSWORD: $PASSWORD"
  echo "  SECURITY_DIR_PATH: $SECURITY_DIR_PATH"
  echo "  SECURITY_FILE_NAME: $SECURITY_FILE_NAME"
  echo "  SETTINGS_DIR_PATH: $SETTINGS_DIR_PATH"
  echo "  SETTINGS_FILE_NAME: $SETTINGS_FILE_NAME"
  echo "  TEMP_DIR_PATH: $TEMP_DIR_PATH"
  echo "  BACKUP_EXTENSION: $BACKUP_EXTENSION"
}

#0. Parse Input and Init variables
MASTER_PASSWORD=
PASSWORD=
SECURITY_DIR_PATH=~/.m2
SECURITY_FILE_NAME=settings-security.xml
SETTINGS_DIR_PATH=~/.m2
SETTINGS_FILE_NAME=settings.xml
TEMP_DIR_PATH=$TMPDIR
BACKUP_EXTENSION=.bak

if [ "$1" == "--help" ]
then
    print_help
    exit
fi

echo "Enter your MasterPassword:"
read -sp "MasterPassword: " MASTER_PASSWORD
echo ""
echo "Enter your Password:"
read -sp "Password: " PASSWORD
echo ""

#1. Generate Master Password by `mvn --encrypt-master-password`
MASTER_PASSWORD=$(mvn --encrypt-master-password $MASTER_PASSWORD | sed 's/\//\\\//g')

#2. Replace Master Password in settings-security.xml by `sed 's/{.*}/{my-new-password}/g' settings-security.xml > $TMPDIR/settings-security.xml`
eval sed 's/{.*}/$MASTER_PASSWORD/g' $SECURITY_DIR_PATH/$SECURITY_FILE_NAME > $TEMP_DIR_PATH/$SECURITY_FILE_NAME
cp $SECURITY_DIR_PATH/$SECURITY_FILE_NAME $SECURITY_DIR_PATH/$SECURITY_FILE_NAME$BACKUP_EXTENSION # Backup
cp $TEMP_DIR_PATH/$SECURITY_FILE_NAME $SECURITY_DIR_PATH/$SECURITY_FILE_NAME
rm -f $TEMP_DIR_PATH/$SECURITY_FILE_NAME

#3. Generate Password by `mvn --encrypt-password`
PASSWORD=$(mvn --encrypt-password $PASSWORD | sed 's/\//\\\//g')

#4. Replace Password in settings.xml
eval sed 's/{.*}/$PASSWORD/g' $SETTINGS_DIR_PATH/$SETTINGS_FILE_NAME > $TEMP_DIR_PATH/$SETTINGS_FILE_NAME
cp $SETTINGS_DIR_PATH/$SETTINGS_FILE_NAME $SETTINGS_DIR_PATH/$SETTINGS_FILE_NAME$BACKUP_EXTENSION
cp $TEMP_DIR_PATH/$SETTINGS_FILE_NAME $SETTINGS_DIR_PATH/$SETTINGS_FILE_NAME
rm -f $TEMP_DIR_PATH/$SETTINGS_FILE_NAME
